### ISSUE TITLE
tensorflow-gpu not available for MacOS

### ISSUE THREAD

**Issue by kgoebber** [Unidata/unidata-users-workshop#14]
This is just an FYI.

Just created the environment for the workshop and tensorflow-gpu is no longer supported for MacOS. I removed that line and everything else, including tensorflow (but not tensorflow-gpu) installed just fine.

**Comment by jrleeman** [comment]
Ugh - It installed last week, but I can confirm this. @ddirks we may need to ping whomever requested that package.

**Comment by pjpokran** [comment]
I just tried and got the same thing. This is not a conda env update, but rather a 

conda env create -f environment.yml

It works if you take tensorflow-gpu out of the environment file.
